# 每天10:00执行

name: "xiaobei_health_auto_run_on_8_A.M."

on:
  push:
  schedule:
    - cron: "0 0 * * *"
    # 这里的时间为 UTC 时间，在 0 点运行，则在北京时间早上 8 点运行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "set up python"
        uses: actions/setup-python@master
        with:
          python-version: 3.9

      - name: install requests
        run: |
          python -m pip install requests
      - name: run xiaobei
        env:
          IDCODE: ${{ secrets.IDCODE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SCKEY: ${{secrets.SCKEY}}
        run: |
          python3.9 ./main.py
